---
resources:
  - name: git-repository-master
    type: git
    source:
      uri: "https://github.com/dani-sc/fhs02-continuous-delivery-concourse.git"
      branch: master

  - name: git-repository-brakeman
    type: git
    source:
      uri: "https://github.com/dani-sc/fhs02-continuous-delivery-concourse.git"
      branch: brakeman
      username: {{github-username}}
      password: {{github-password}}
  
  - name: docker-image-blog
    type: docker-image
    source:
      repository: danisc/fhs02-t01-blog
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

jobs:
- name: build-blog-image
  plan:
  - get: git-repository-master
    trigger: true
  - put: docker-image-blog
    params: {build: git-repository-master}

- name: integration-tests
  build_logs_to_retain: 3
  plan:
  - get: docker-image-blog
    trigger: true
    passed: [build-blog-image]
  - task: run-integration-tests
    image: docker-image-blog
    config:
      platform: linux
      run:
        path: sh
        args:
          - -exc
          - |
            cd /blog
            bundle exec rspec

- name: security-checks
  build_logs_to_retain: 3
  plan:
  - get: docker-image-blog
    trigger: true
    passed: [integration-tests]
  - get: git-repository-brakeman
  - task: run-brakeman
    image: docker-image-blog
    config:
      platform: linux
      inputs:
        - name: git-repository-brakeman
      outputs:
        - name: git-repository-brakeman-modified
      run:
        path: sh
        args:
          - -exc
          - |
            git clone git-repository-brakeman git-repository-brakeman-modified
            brakeman /blog -z -o brakeman_output.json --compare git-repository-brakeman-modified/brakeman_output.json
            cp brakeman_output.json git-repository-brakeman-modified/brakeman_output.json
            cd git-repository-brakeman-modified
            git checkout brakeman
            git add .
            git config --global user.email "daniel.scheffkn@gmail.com"
            git config --global  user.name "Daniel Scheffknecht"
            git commit -m "[ci skip] Update brakeman output file"
  - put: git-repository-brakeman
    params: {repository: git-repository-brakeman-modified}
