---
resources:
  - name: git-repository
    type: git
    source:
      uri: "https://github.com/dani-sc/fhs02-continuous-delivery-concourse.git"
      branch: master
  - name: 3m
    type: time
    source: { interval: 5m }

jobs:
- name: integration-tests
  build_logs_to_retain: 10
  plan:
  - get: 3m
    trigger: true
  - task: run-integration-tests
    config:
      platform: linux

      image_resource:
        type: docker-image
        source: { repository: ruby, tag: 2.4.1 }

      inputs:
      - name: git-repository

      run:
        path: sh
        dir: git-repository
        args:
          - -exc
          - |
            cd blog
            bundle exec rspec
