---
resources:
  - name: git-repository
    type: git
    source:
      uri: "https://github.com/dani-sc/fhs02-continuous-delivery-concourse.git"
      branch: master
  
  - name: docker-image-blog
    type: docker-image
    source:
      repository: danisc/fhs02-t01-blog
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

jobs:
- name: build-blog-image
  plan:
  - get: git-repository
    trigger: true
  - put: docker-image-blog
    params: {build: git-repository}

- name: integration-tests
  build_logs_to_retain: 10
  plan:
  - get: docker-image-blog
    trigger: true
    passed: [build-blog-image]
  - task: run-integration-tests
    image: docker-image-blog
    config:
      platform: linux
      run:
        path: sh
        args:
          - -exc
          - |
            cd /blog
            bundle exec rspec
